set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tomasiser/vim-code-dark'

Plugin 'majutsushi/tagbar'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

Plugin 'scrooloose/nerdcommenter'
Plugin 'godlygeek/tabular'

Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'hotwatermorning/auto-git-diff'
Plugin 'habamax/vim-rst'

" FOR FUNCTION HIGHLIGHT https://vimawesome.com/plugin/vim-cpp-enhanced-highlight
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'kergoth/vim-bitbake.git'

Plugin 'joe-skb7/cscope-maps'

Plugin 'tpope/vim-obsession'

call vundle#end()            " required
filetype plugin indent on    " required

"
" Put your non-Plugin stuff after this line

syntax on
set scrolloff=1
colorscheme codedark

set enc=utf-8
set ls=2
set mouse=a
set ttymouse=xterm2
set splitbelow
set number
" disable folding
set nofoldenable

" Tab settings
set tabstop=8
set softtabstop=8
set shiftwidth=8
set expandtab
set colorcolumn=80

set is hlsearch
set cursorline

if has("unix")
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
    set clipboard=unnamed
  else
    set clipboard=unnamedplus
  endif
endif

set wildmenu
set wildmode=longest:full,full

" set up different cursor for insert, replace and normal modes
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Short keys
nmap <F8> :TagbarToggle<CR>
map <F5> i -- Andrew Lalaev <andrey.lalaev@gmail.com> <esc>:r !date -R <CR>i<Backspace> <esc>

set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

set omnifunc=syntaxcomplete#Complete
:autocmd InsertEnter,InsertLeave * set cul!

set pumheight=7
set completeopt-=preview

let g:NERDSpaceDelims=1
let g:NERDCompactSexyComs=1
let g:NERDCustomDelimiters={ 'c': { 'left': '/**','right': '*/' } }

"auto close {
function! s:CloseBracket()
    let line = getline('.')
    if line =~# '^\s*\(struct\|class\|enum\) '
        "return "{\<Enter>}\<Esc>O"
        return "{\<Enter>};\<Esc>O"
    elseif searchpair('(', '', ')', 'bmn', '', line('.'))
        " Probably inside a function call. Close it off.
        return "{\<Enter>});\<Esc>O"
    else
        return "{\<Enter>}\<Esc>O"
    endif
endfunction
inoremap <expr> {<Enter> <SID>CloseBracket()

nnoremap <silent> <Esc><Esc> :noh<CR> :call clearmatches()<CR>
let g:rst_syntax_code_list = {
    \ 'vim': ['vim'],
    \ 'java': ['java'],
    \ 'cpp': ['cpp', 'c++'],
    \ 'c': ['c', 'c'],
    \ 'lisp': ['lisp'],
    \ 'php': ['php'],
    \ 'python': ['python'],
    \ 'perl': ['perl'],
    \ 'sh': ['sh'],
    \ }
