export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="candy"

CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"

plugins=(git rust)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

alias grep="grep --color=auto"
alias ip="ip -c"
alias cal="ncal -b"
alias bat="batcat --pager=never"
alias uipk="ar -xv"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"
export FZF_DEFAULT_COMMAND='rg --files --follow --hidden --no-ignore'

export PATH=${PATH}:~/.cargo/bin/

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)
